apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-cd-demo-ingress-staging
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: staging.demo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ci-cd-demo-service-staging
            port:
              number: 80
